# This is a GitHub Action to sync a fork with the original repository.
#
# To use this action:
# 1. Create a new file in your forked repository named `.github/workflows/sync-fork.yml`.
# 2. Copy and paste the code below into the new file.
# 3. The `cron` schedule is set to run every minute. You can change this to your preference.
#    Use https://crontab.guru to help you create a cron schedule.
# 4. This action uses the `GITHUB_TOKEN` secret, which is automatically available to all repositories.
#    You do not need to create this secret.

name: Sync Fork

on:
  schedule:
    - cron: '* * * * *' # This runs the action every minute
  workflow_dispatch: # This allows you to run the action manually from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          # We need to fetch all branches and tags so that we can push them to the fork.
          fetch-depth: 0

      - name: Sync Fork with Upstream
        run: |
          # It is best practice to set the user name and email for the git commits.
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
          # This command adds the original repository as a remote called "upstream".
          # Replace 'UPSTREAM_REPO_URL' with the URL of the original repository.
          # For example: https://github.com/upstream/repo.git
          git remote add upstream https://github.com/UPSTREAM_OWNER/UPSTREAM_REPO_NAME.git
          
          # This command fetches all the branches from the upstream repository.
          git fetch upstream
          
          # This command gets all the branch names from the upstream and loops through them.
          for branch in $(git branch -r | grep 'upstream/' | sed 's/upstream\///'); do
            # This checks out each branch from the upstream repository.
            git checkout $branch
            # This pulls the latest changes from the upstream branch.
            git pull upstream $branch
            # This pushes the changes to your forked repository.
            git push origin $branch
          done
          
          # This command fetches all the tags from the upstream repository.
          git fetch upstream --tags
          
          # This command pushes all the tags to your forked repository.
          git push origin --tags
        env:
          # The GITHUB_TOKEN is a special access token that you can use to authenticate on behalf of GitHub Actions.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

